"""change column name to loginAttempt (from loginAttempts) + add default value for the column of 0

Revision ID: 048d2eb8a5da
Revises: 397d738be806
Create Date: 2024-12-22 16:10:54.923191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '048d2eb8a5da'
down_revision = '397d738be806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loginAttempt', sa.Integer(), nullable=True, server_default='0'))
        batch_op.drop_column('loginAttempts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loginAttempts', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('loginAttempt')

    # ### end Alembic commands ###
