"""feat: isVerified added to User

Revision ID: 1955d7f6934a
Revises: b0026bc419c8
Create Date: 2024-12-17 07:34:56.928370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1955d7f6934a'
down_revision = 'b0026bc419c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isVerified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isVerified')

    # ### end Alembic commands ###
