"""empty message

Revision ID: 397d738be806
Revises: 1955d7f6934a
Create Date: 2024-12-22 15:50:20.725604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397d738be806'
down_revision = '1955d7f6934a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loginAttempts', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('last_failed_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_failed_login')
        batch_op.drop_column('loginAttempts')

    # ### end Alembic commands ###
